### ISSUE TITLE
Bugs de inicio

### ISSUE THREAD

**Issue by fcogarica** [CristoferCD/PorD10#2]
W10m build  14393.693    640xl 

1) Login automático se vuelve activar cada vez que abro la app... no importa si lo desactivo desde la ventada de login o desde la opción en configuración.
2) La ventanita de usuario se auto selecciona por defecto cada vez que abro la app, por lo que siempre me aparece el teclado aunque se este logueando.

**Comment by CristoferCD** [comment]
Anotado.
Gracias.

**Comment by fcogarica** [comment]
W10m build 14393.693 640xl
Cuando estas en el menu principal y le das a atrás vuelves al menu de login pero en esta ocasión no aparece ni el nombre de usuario ni la contraseña, por lo que tienes que logearte de nuevo...

**Comment by CristoferCD** [comment]
Solucionado
