### ISSUE TITLE
Titulos tapados

### ISSUE THREAD

**Issue by fcogarica** [CristoferCD/PorD10#5]
W10m Lumia 640xl
version de la app 1.7.8.0

El titulo de la serie o película queda tapado por la imagen de esta en el selector de episodios
![wp_ss_20170312_0005](https://cloud.githubusercontent.com/assets/20754973/23831762/c9ac89a2-0727-11e7-8b61-035b2762dbdf.png)

**Comment by CristoferCD** [comment]
Solucionado en 1.9.4
