### ISSUE TITLE
La app crashea

### ISSUE THREAD

**Issue by RosGar** [CristoferCD/PorD10#7]
Buenas, la app en Windows 10 PC crashea cada cierto tiempo, sobre todo cuando te metes a alguna serie.
En mi lumia 730 se cierra cuando cierro un vídeo y voy a poner otro.

**Comment by CristoferCD** [comment]
Eso quizás tiene que ver con que la web se cae cada 2x3, tengo que tener mas controlado el estado de las conexiones.
Lo relacionado con la reproducción de videos lo voy a cambiar bastante para la próxima versión.
Gracias por el aviso.
