### ISSUE TITLE
PorD10 no mantiene la pantalla encendida

### ISSUE THREAD

**Issue by RosGar** [CristoferCD/PorD10#8]
Cuando veo alguna serie o película desde el móvil la pantalla se mantiene encendida, pero cuando envío la imagen a traves de miracast a mi smart tv sin continuum al cabo de pasar unos min el móvil se bloquea y la app se cierra en la smart tv y tengo que volver a conectarme a ella.
La solución se puedes hacerlo es que pord10 mantenga la pantalla encendida y no se bloquee.
Un saludo

**Comment by CristoferCD** [comment]
Solucionado
