### ISSUE TITLE
Problema pantalla completa 

### ISSUE THREAD

**Issue by fcogarica** [CristoferCD/PorD10#9]
La actualización 1.9.2.0 tiene un problema al poner el video en pantalla completa... con esto de que todo sale en la misma ventana, la barra de abajo molesta al reproductor de video cuando esta en pantalla completa.

![image](https://user-images.githubusercontent.com/20754973/27099697-0f7660b4-507c-11e7-9e77-8d85c7d97fcb.png)

Pasa tanto en PC como en mobile

**Comment by CristoferCD** [comment]
Solucionado en 1.9.4
